spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:travel_db
    username: sa
    password: password
  h2.console.enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect

weather:
  url: "https://api.weather.yandex.ru/v2/informers"

